### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by ChinaGodzilla** [kivymd/KivyMDBuilder#2]
Amazing, the designer will greatly improve mobile development in PYTHON.

**Comment by ChinaGodzilla** [comment]
I support publishing commercial versions and I am willing to buy them.

**Comment by peterstavrou** [comment]
I also support publishing a commerical version. I think many of us are willing to pay a one-time fee for something like this.

**Comment by ProtDos** [comment]
@ChinaGodzilla @PeterStavrou how much are you willing to pay (one-time) if I created something like that?

**Comment by ChinaGodzilla** [comment]
@ProtDos   about 100 - 500 Dollar

**Comment by ChinaGodzilla** [comment]
@ProtDos   a year

**Comment by ProtDos** [comment]
@ChinaGodzilla okay. I may publish a commercial version
