### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by Tmonitor745** [kivymd/KivyMDBuilder#9]
I was wondering if this was still an active project. If it isnt you should at least post what you made so far

**Comment by 9acca9** [comment]
i was... wondering the same!

**Comment by SouthpawIN** [comment]
I would really like to play with this. Has anyone stumbled on a good alternative?

**Comment by Tmonitor745** [comment]
> I would really like to play with this. Has anyone stumbled on a good alternative?

ive tried there really is nothing
